"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Cloud,
  Upload,
  FileUp,
  Clipboard,
  CheckCircle2,
  ArrowLeft,
  Terminal,
} from "lucide-react";
import toast from "react-hot-toast";
import { useRouter } from "next/navigation";
import Link from "next/link";

export default function M365ImportPage() {
  const router = useRouter();
  const [mode, setMode] = useState<"paste" | "file">("paste");
  const [tenantName, setTenantName] = useState("");
  const [displayName, setDisplayName] = useState("");
  const [label, setLabel] = useState("");
  const [rawJson, setRawJson] = useState("");
  const [importing, setImporting] = useState(false);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      setRawJson(ev.target?.result as string);
    };
    reader.readAsText(file);
  };

  const handleImport = async () => {
    if (!tenantName) {
      toast.error("Tenant name is required");
      return;
    }
    if (!rawJson.trim()) {
      toast.error("Paste or upload a JSON report first");
      return;
    }

    let parsed;
    try {
      parsed = JSON.parse(rawJson);
    } catch {
      toast.error("Invalid JSON format");
      return;
    }

    setImporting(true);
    try {
      const res = await fetch("/api/m365/import", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          tenantName,
          displayName: displayName || tenantName,
          defaultDomain: tenantName.replace(".onmicrosoft.com", ".com"),
          resources: Array.isArray(parsed) ? parsed : parsed.resources || [parsed],
          label,
        }),
      });
      const json = await res.json();
      if (json.success) {
        toast.success(json.message);
        router.push("/m365");
      } else {
        toast.error(json.error || "Import failed");
      }
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Import failed");
    } finally {
      setImporting(false);
    }
  };

  return (
    <div className="space-y-6 max-w-4xl">
      <Link href="/m365">
        <Button variant="ghost" size="sm">
          <ArrowLeft className="h-4 w-4" /> Back to M365 Dashboard
        </Button>
      </Link>

      <div>
        <h2 className="text-2xl font-bold text-dsc-text">Import M365 DSC Report</h2>
        <p className="text-sm text-dsc-text-secondary mt-1">
          Import a Microsoft365DSC JSON report generated by New-M365DSCReportFromConfiguration
        </p>
      </div>

      {/* How to generate */}
      <Card className="border-dsc-blue/20 bg-dsc-blue-50/30">
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <Terminal className="h-4 w-4 text-dsc-blue" />
            How to Generate a JSON Report
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3 text-sm text-dsc-text-secondary">
            <p>1. Export your tenant configuration:</p>
            <pre className="code-editor bg-dsc-surface rounded-lg p-3 text-xs border border-dsc-border overflow-x-auto">
{`Export-M365DSCConfiguration -Credential $cred \\
  -Components @("AADConditionalAccessPolicy","EXOOrganizationConfig","SPOTenantSettings","TeamsMeetingPolicy") \\
  -Path C:\\DSC -FileName "TenantConfig.ps1"`}
            </pre>
            <p>2. Generate the JSON report:</p>
            <pre className="code-editor bg-dsc-surface rounded-lg p-3 text-xs border border-dsc-border overflow-x-auto">
{`New-M365DSCReportFromConfiguration \\
  -Type JSON \\
  -ConfigurationPath "C:\\DSC\\TenantConfig.ps1" \\
  -OutputPath "C:\\DSC\\TenantReport.json"`}
            </pre>
            <p>3. Upload or paste the resulting JSON file below.</p>
          </div>
        </CardContent>
      </Card>

      {/* Tenant Info */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Tenant Information</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Input
              label="Tenant Name"
              placeholder="contoso.onmicrosoft.com"
              value={tenantName}
              onChange={(e) => setTenantName(e.target.value)}
            />
            <Input
              label="Display Name"
              placeholder="Contoso Corporation"
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
            />
            <Input
              label="Snapshot Label (optional)"
              placeholder="Q1 2026 Baseline"
              value={label}
              onChange={(e) => setLabel(e.target.value)}
            />
          </div>
        </CardContent>
      </Card>

      {/* Mode Toggle */}
      <div className="flex gap-2">
        <Button variant={mode === "paste" ? "primary" : "outline"} size="sm" onClick={() => setMode("paste")}>
          <Clipboard className="h-4 w-4" /> Paste JSON
        </Button>
        <Button variant={mode === "file" ? "primary" : "outline"} size="sm" onClick={() => setMode("file")}>
          <FileUp className="h-4 w-4" /> Upload File
        </Button>
      </div>

      {/* Input */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <Cloud className="h-4 w-4 text-dsc-blue" />
            M365DSC JSON Report
          </CardTitle>
          <CardDescription>
            Output from New-M365DSCReportFromConfiguration -Type JSON
          </CardDescription>
        </CardHeader>
        <CardContent>
          {mode === "paste" ? (
            <Textarea
              placeholder='[{"ResourceName": "AADConditionalAccessPolicy", "DisplayName": "Require MFA", ...}]'
              className="code-editor min-h-[250px]"
              value={rawJson}
              onChange={(e) => setRawJson(e.target.value)}
            />
          ) : (
            <div className="border-2 border-dashed border-dsc-border rounded-lg p-8 text-center">
              <Upload className="h-8 w-8 text-dsc-text-secondary mx-auto mb-3" />
              <p className="text-sm text-dsc-text-secondary mb-3">Drop a .json file here</p>
              <input type="file" accept=".json" onChange={handleFileUpload} className="hidden" id="m365-upload" />
              <label htmlFor="m365-upload" className="cursor-pointer">
                <span className="inline-flex items-center justify-center gap-2 rounded-lg text-sm font-medium border border-dsc-border bg-dsc-surface text-dsc-text hover:bg-dsc-bg h-8 px-3">
                  Choose File
                </span>
              </label>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Import Button */}
      <div className="flex gap-3">
        <Button onClick={handleImport} disabled={importing || !tenantName || !rawJson.trim()} size="lg">
          <CheckCircle2 className="h-4 w-4" />
          {importing ? "Importing..." : "Import Report"}
        </Button>
      </div>
    </div>
  );
}

