// Realistic Agent 365 Registry demo data
// Simulates GET /beta/copilot/admin/catalog/packages response

export const demoAgents = [
  // Microsoft agents
  {
    packageId: "P_ms-copilot-chat-001",
    displayName: "Microsoft 365 Copilot Chat",
    type: "MICROSOFT" as const,
    shortDescription: "AI-powered chat assistant integrated across Microsoft 365 apps",
    publisher: "Microsoft Corporation",
    supportedHosts: ["Copilot", "Teams", "Outlook", "Word", "Excel", "PowerPoint"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "3.2.1",
    availableTo: "all",
    deployedTo: "all",
    isPinned: true,
    pinnedScope: "all",
    riskCount: 0,
    isBlocked: false,
  },
  {
    packageId: "P_ms-researcher-002",
    displayName: "Researcher",
    type: "MICROSOFT" as const,
    shortDescription: "Deep research agent that synthesizes information from web and work data into comprehensive reports",
    publisher: "Microsoft Corporation",
    supportedHosts: ["Copilot"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "2.1.0",
    availableTo: "all",
    deployedTo: "all",
    isPinned: true,
    pinnedScope: "all",
    riskCount: 0,
    isBlocked: false,
  },
  {
    packageId: "P_ms-analyst-003",
    displayName: "Analyst",
    type: "MICROSOFT" as const,
    shortDescription: "Data analysis agent that helps create visualizations and insights from your organizational data",
    publisher: "Microsoft Corporation",
    supportedHosts: ["Copilot", "Excel"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "1.5.0",
    availableTo: "all",
    deployedTo: "all",
    isPinned: false,
    riskCount: 0,
    isBlocked: false,
  },

  // External partner agents
  {
    packageId: "P_ext-servicenow-010",
    displayName: "ServiceNow IT Agent",
    type: "EXTERNAL" as const,
    shortDescription: "Create, update, and track IT service tickets directly from Copilot and Teams",
    publisher: "ServiceNow, Inc.",
    supportedHosts: ["Copilot", "Teams"],
    elementTypes: ["DeclarativeAgent", "Bots"],
    platform: "web",
    version: "4.1.2",
    availableTo: "all",
    deployedTo: "all",
    isPinned: false,
    riskCount: 0,
    isBlocked: false,
  },
  {
    packageId: "P_ext-salesforce-011",
    displayName: "Salesforce CRM Agent",
    type: "EXTERNAL" as const,
    shortDescription: "Access Salesforce CRM data, manage leads, and update opportunities from Microsoft 365",
    publisher: "Salesforce, Inc.",
    supportedHosts: ["Copilot", "Outlook", "Teams"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "2.3.0",
    availableTo: "all",
    deployedTo: "specific",
    isPinned: false,
    riskCount: 2,
    isBlocked: false,
  },
  {
    packageId: "P_ext-adobe-012",
    displayName: "Adobe Acrobat for Copilot",
    type: "EXTERNAL" as const,
    shortDescription: "Summarize, analyze, and extract insights from PDF documents using Copilot",
    publisher: "Adobe Inc.",
    supportedHosts: ["Copilot", "Word"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "1.8.5",
    availableTo: "all",
    deployedTo: "all",
    isPinned: false,
    riskCount: 0,
    isBlocked: false,
  },
  {
    packageId: "P_ext-jira-013",
    displayName: "Jira Cloud Agent",
    type: "EXTERNAL" as const,
    shortDescription: "Manage Jira issues, sprints, and project boards from Teams and Copilot",
    publisher: "Atlassian",
    supportedHosts: ["Copilot", "Teams"],
    elementTypes: ["DeclarativeAgent", "Bots"],
    platform: "web",
    version: "3.0.1",
    availableTo: "all",
    deployedTo: "none",
    isPinned: false,
    riskCount: 1,
    isBlocked: false,
  },
  {
    packageId: "P_ext-zoom-014",
    displayName: "Zoom Workplace Agent",
    type: "EXTERNAL" as const,
    shortDescription: "Schedule and manage Zoom meetings, access recordings and transcripts",
    publisher: "Zoom Video Communications",
    supportedHosts: ["Copilot", "Outlook"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "2.0.0",
    availableTo: "specific",
    deployedTo: "none",
    isPinned: false,
    riskCount: 0,
    isBlocked: true,
  },

  // Custom org agents
  {
    packageId: "P_custom-hr-020",
    displayName: "Contoso HR Assistant",
    type: "CUSTOM" as const,
    shortDescription: "Answer employee questions about benefits, PTO policies, onboarding, and HR procedures",
    publisher: "Contoso IT",
    supportedHosts: ["Copilot", "Teams"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "2.1.0",
    availableTo: "all",
    deployedTo: "all",
    isPinned: true,
    pinnedScope: "all",
    riskCount: 0,
    isBlocked: false,
    hasEmbeddedFiles: true,
    sensitivityLabel: "Internal",
    ownerDisplayName: "Alice Johnson",
  },
  {
    packageId: "P_custom-legal-021",
    displayName: "Legal Contract Reviewer",
    type: "CUSTOM" as const,
    shortDescription: "Review contracts, flag risk clauses, and compare against standard templates",
    publisher: "Contoso Legal",
    supportedHosts: ["Copilot", "Word"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "1.3.0",
    availableTo: "specific",
    deployedTo: "specific",
    isPinned: false,
    riskCount: 3,
    isBlocked: false,
    hasEmbeddedFiles: true,
    sensitivityLabel: "Confidential",
    ownerDisplayName: "Bob Martinez",
  },
  {
    packageId: "P_custom-sales-022",
    displayName: "Sales Coach",
    type: "CUSTOM" as const,
    shortDescription: "Provide real-time coaching tips, objection handling, and competitive intelligence during sales calls",
    publisher: "Contoso Sales Ops",
    supportedHosts: ["Copilot", "Teams"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "1.0.2",
    availableTo: "specific",
    deployedTo: "specific",
    isPinned: true,
    pinnedScope: "Sales Department",
    riskCount: 0,
    isBlocked: false,
    hasEmbeddedFiles: true,
    sensitivityLabel: "Internal",
    ownerDisplayName: "Carol Chen",
  },
  {
    packageId: "P_custom-it-helpdesk-023",
    displayName: "IT Helpdesk Bot",
    type: "CUSTOM" as const,
    shortDescription: "Troubleshoot common IT issues, reset passwords, and escalate tickets to support staff",
    publisher: "Contoso IT",
    supportedHosts: ["Copilot", "Teams"],
    elementTypes: ["DeclarativeAgent", "Bots"],
    platform: "web",
    version: "3.5.1",
    availableTo: "all",
    deployedTo: "all",
    isPinned: false,
    riskCount: 0,
    isBlocked: false,
    ownerDisplayName: "Dave Wilson",
  },
  {
    packageId: "P_custom-finance-024",
    displayName: "Finance Report Generator",
    type: "CUSTOM" as const,
    shortDescription: "Generate financial reports, budget summaries, and expense analyses from organizational data",
    publisher: "Contoso Finance",
    supportedHosts: ["Copilot", "Excel"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "1.1.0",
    availableTo: "specific",
    deployedTo: "none",
    isPinned: false,
    riskCount: 1,
    isBlocked: false,
    hasEmbeddedFiles: true,
    sensitivityLabel: "Highly Confidential",
    ownerDisplayName: "Eve Thompson",
  },

  // Shared agents
  {
    packageId: "P_shared-meeting-030",
    displayName: "Meeting Notes Summarizer",
    type: "SHARED" as const,
    shortDescription: "Automatically summarize meeting notes and extract action items from Teams meetings",
    publisher: "Frank Lee",
    supportedHosts: ["Copilot", "Teams"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "1.0.0",
    availableTo: "specific",
    deployedTo: "none",
    isPinned: false,
    riskCount: 0,
    isBlocked: false,
    ownerDisplayName: "Frank Lee",
  },
  {
    packageId: "P_shared-email-031",
    displayName: "Email Drafter Pro",
    type: "SHARED" as const,
    shortDescription: "Draft professional emails with customizable tone, length, and formatting options",
    publisher: "Grace Kim",
    supportedHosts: ["Copilot", "Outlook"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "1.2.0",
    availableTo: "specific",
    deployedTo: "none",
    isPinned: false,
    riskCount: 0,
    isBlocked: false,
    ownerDisplayName: "Grace Kim",
  },
  {
    packageId: "P_shared-ownerless-032",
    displayName: "Project Tracker Agent",
    type: "SHARED" as const,
    shortDescription: "Track project milestones, deadlines, and team assignments across Planner and Teams",
    publisher: "Former Employee",
    supportedHosts: ["Copilot", "Teams"],
    elementTypes: ["DeclarativeAgent"],
    platform: "web",
    version: "0.9.0",
    availableTo: "specific",
    deployedTo: "none",
    isPinned: false,
    riskCount: 0,
    isBlocked: false,
    isOwnerless: true,
  },
];
