// Realistic Microsoft Purview demo data
// Models the Graph API responses from:
//   GET /security/dataSecurityAndGovernance/sensitivityLabels
//   POST /users/{id}/dataSecurityAndGovernance/protectionScopes/compute

export const demoSensitivityLabels = [
  // ─── Top-level labels ─────────────────────────────────
  {
    labelId: "a1b2c3d4-0001-4000-8000-000000000001",
    name: "Public",
    displayName: "Public",
    description: "Unrestricted data intended for public consumption. No protection applied.",
    tooltip: "Use for data that can be freely shared with anyone, including external parties.",
    color: "#38A169",
    priority: 0,
    sensitivity: 0,
    isEnabled: true,
    isDefault: false,
    isEndpointProtectionEnabled: false,
    hasProtection: false,
    applicableTo: ["email", "file", "site", "teamwork"],
    contentFormats: ["file", "email"],
    applicationMode: "manual",
    actionSource: "manual",
    isAppliable: true,
  },
  {
    labelId: "a1b2c3d4-0002-4000-8000-000000000002",
    name: "General",
    displayName: "General",
    description: "Business data not intended for public consumption. Default label for most content.",
    tooltip: "Apply to everyday business data that doesn't require special protection.",
    color: "#3182CE",
    priority: 1,
    sensitivity: 1,
    isEnabled: true,
    isDefault: true,
    isEndpointProtectionEnabled: false,
    hasProtection: false,
    applicableTo: ["email", "file", "site", "teamwork", "unifiedGroup"],
    contentFormats: ["file", "email"],
    applicationMode: "manual",
    actionSource: "manual",
    isAppliable: false, // parent label
    sublabels: [
      {
        labelId: "a1b2c3d4-0002-4001-8000-000000000001",
        name: "General\\Anyone (unrestricted)",
        displayName: "Anyone (unrestricted)",
        description: "Data that doesn't require protection but shouldn't be shared publicly.",
        tooltip: "No encryption. Content can be shared with anyone.",
        color: "#3182CE",
        priority: 2,
        sensitivity: 1,
        isEnabled: true,
        isDefault: true,
        hasProtection: false,
        applicableTo: ["email", "file"],
        applicationMode: "manual",
      },
      {
        labelId: "a1b2c3d4-0002-4002-8000-000000000002",
        name: "General\\All Employees (unrestricted)",
        displayName: "All Employees (unrestricted)",
        description: "Data accessible to all employees without encryption.",
        tooltip: "No encryption. Visible to all internal users.",
        color: "#3182CE",
        priority: 3,
        sensitivity: 2,
        isEnabled: true,
        isDefault: false,
        hasProtection: false,
        applicableTo: ["email", "file", "site"],
        applicationMode: "manual",
      },
    ],
  },
  {
    labelId: "a1b2c3d4-0003-4000-8000-000000000003",
    name: "Confidential",
    displayName: "Confidential",
    description: "Sensitive business data that could cause damage to the business if shared with unauthorized people.",
    tooltip: "Apply to sensitive business data. Encryption and access controls may be applied.",
    color: "#D69E2E",
    priority: 4,
    sensitivity: 3,
    isEnabled: true,
    isDefault: false,
    isEndpointProtectionEnabled: true,
    hasProtection: true,
    applicableTo: ["email", "file", "site", "teamwork", "unifiedGroup", "schematizedData"],
    contentFormats: ["file", "email"],
    applicationMode: "manual",
    actionSource: "manual",
    isAppliable: false,
    sublabels: [
      {
        labelId: "a1b2c3d4-0003-4001-8000-000000000001",
        name: "Confidential\\All Employees",
        displayName: "All Employees",
        description: "Confidential data accessible to all employees. Encrypted with org-wide key.",
        tooltip: "Encrypted. All employees can view. External sharing blocked.",
        color: "#D69E2E",
        priority: 5,
        sensitivity: 3,
        isEnabled: true,
        hasProtection: true,
        isEndpointProtectionEnabled: true,
        applicableTo: ["email", "file", "site"],
        applicationMode: "recommended",
      },
      {
        labelId: "a1b2c3d4-0003-4002-8000-000000000002",
        name: "Confidential\\Anyone (protected)",
        displayName: "Anyone (protected)",
        description: "Confidential data that can be shared externally with encryption protection.",
        tooltip: "Encrypted. Can be shared externally but recipients need to authenticate.",
        color: "#D69E2E",
        priority: 6,
        sensitivity: 3,
        isEnabled: true,
        hasProtection: true,
        applicableTo: ["email", "file"],
        applicationMode: "manual",
      },
      {
        labelId: "a1b2c3d4-0003-4003-8000-000000000003",
        name: "Confidential\\Specific People",
        displayName: "Specific People",
        description: "Confidential data restricted to named individuals only.",
        tooltip: "Encrypted. Only specified users can access.",
        color: "#D69E2E",
        priority: 7,
        sensitivity: 4,
        isEnabled: true,
        hasProtection: true,
        isEndpointProtectionEnabled: true,
        applicableTo: ["email", "file"],
        applicationMode: "manual",
      },
    ],
  },
  {
    labelId: "a1b2c3d4-0004-4000-8000-000000000004",
    name: "Highly Confidential",
    displayName: "Highly Confidential",
    description: "Very sensitive business data that would cause serious damage if shared with unauthorized people. Includes trade secrets, M&A data, and executive communications.",
    tooltip: "Apply to the most sensitive data. Strong encryption and strict access controls enforced.",
    color: "#E53E3E",
    priority: 8,
    sensitivity: 5,
    isEnabled: true,
    isDefault: false,
    isEndpointProtectionEnabled: true,
    hasProtection: true,
    applicableTo: ["email", "file", "site", "teamwork", "unifiedGroup", "schematizedData"],
    contentFormats: ["file", "email"],
    applicationMode: "manual",
    actionSource: "manual",
    isAppliable: false,
    sublabels: [
      {
        labelId: "a1b2c3d4-0004-4001-8000-000000000001",
        name: "Highly Confidential\\All Employees",
        displayName: "All Employees",
        description: "Highly confidential data accessible to all employees with strong encryption.",
        tooltip: "Strong encryption. All employees can view. No external sharing. No printing.",
        color: "#E53E3E",
        priority: 9,
        sensitivity: 5,
        isEnabled: true,
        hasProtection: true,
        isEndpointProtectionEnabled: true,
        applicableTo: ["email", "file", "site"],
        applicationMode: "automatic",
      },
      {
        labelId: "a1b2c3d4-0004-4002-8000-000000000002",
        name: "Highly Confidential\\Specific People",
        displayName: "Specific People",
        description: "Most restricted label. Only named individuals can access. Full audit trail.",
        tooltip: "Maximum protection. Only specified users. No forwarding, printing, or copying.",
        color: "#E53E3E",
        priority: 10,
        sensitivity: 6,
        isEnabled: true,
        hasProtection: true,
        isEndpointProtectionEnabled: true,
        applicableTo: ["email", "file"],
        applicationMode: "manual",
      },
      {
        labelId: "a1b2c3d4-0004-4003-8000-000000000003",
        name: "Highly Confidential\\Board Members Only",
        displayName: "Board Members Only",
        description: "Restricted to board of directors. Used for M&A, executive compensation, and legal matters.",
        tooltip: "Board-only access. Maximum encryption. Full DLP enforcement.",
        color: "#E53E3E",
        priority: 11,
        sensitivity: 7,
        isEnabled: true,
        hasProtection: true,
        isEndpointProtectionEnabled: true,
        applicableTo: ["email", "file"],
        applicationMode: "manual",
      },
    ],
  },
  {
    labelId: "a1b2c3d4-0005-4000-8000-000000000005",
    name: "Personal",
    displayName: "Personal",
    description: "Non-business data for personal use. No organizational protection applied.",
    tooltip: "Use for personal, non-business content.",
    color: "#718096",
    priority: 12,
    sensitivity: 0,
    isEnabled: true,
    isDefault: false,
    isEndpointProtectionEnabled: false,
    hasProtection: false,
    applicableTo: ["email", "file"],
    contentFormats: ["file", "email"],
    applicationMode: "manual",
    actionSource: "manual",
    isAppliable: true,
  },
];

// Protection scopes — simulates POST /users/{id}/dataSecurityAndGovernance/protectionScopes/compute
export const demoProtectionScopes = [
  // Enterprise AI apps
  {
    userId: "user-alice-001",
    userDisplayName: "Alice Johnson (Marketing)",
    activities: ["uploadText", "downloadText"],
    executionMode: "evaluateInline",
    locationType: "policyLocationApplication",
    locationValue: "Microsoft Copilot (83ef208a-0396-4893-9d4f-d36efbffc8bd)",
    policyActions: [],
    restrictionAction: null,
  },
  {
    userId: "user-alice-001",
    userDisplayName: "Alice Johnson (Marketing)",
    activities: ["uploadFile"],
    executionMode: "evaluateOffline",
    locationType: "policyLocationApplication",
    locationValue: "Microsoft Copilot (83ef208a-0396-4893-9d4f-d36efbffc8bd)",
    policyActions: [{ action: "restrictAccess", restrictionAction: "block" }],
    restrictionAction: "block",
  },
  {
    userId: "user-bob-002",
    userDisplayName: "Bob Martinez (Legal)",
    activities: ["uploadText", "uploadFile", "downloadText", "downloadFile"],
    executionMode: "evaluateInline",
    locationType: "policyLocationApplication",
    locationValue: "Legal Contract Reviewer (custom-legal-021)",
    policyActions: [{ action: "evaluateClassification", restrictionAction: null }],
    restrictionAction: null,
  },
  {
    userId: "user-bob-002",
    userDisplayName: "Bob Martinez (Legal)",
    activities: ["uploadFile", "downloadFile"],
    executionMode: "evaluateOffline",
    locationType: "policyLocationApplication",
    locationValue: "Salesforce CRM Agent (ext-salesforce-011)",
    policyActions: [{ action: "restrictAccess", restrictionAction: "block" }],
    restrictionAction: "block",
  },
  // Network/domain scopes
  {
    userId: null,
    userDisplayName: "Tenant-wide Policy",
    activities: ["uploadText", "uploadFile", "downloadText", "downloadFile"],
    executionMode: "evaluateOffline",
    locationType: "policyLocationDomain",
    locationValue: "dropbox.com",
    policyActions: [{ action: "restrictAccess", restrictionAction: "block" }],
    restrictionAction: "block",
  },
  {
    userId: null,
    userDisplayName: "Tenant-wide Policy",
    activities: ["uploadText", "uploadFile"],
    executionMode: "evaluateOffline",
    locationType: "policyLocationDomain",
    locationValue: "personal-gmail.com",
    policyActions: [{ action: "restrictAccess", restrictionAction: "block" }],
    restrictionAction: "block",
  },
  {
    userId: null,
    userDisplayName: "Tenant-wide Policy",
    activities: ["uploadText", "downloadText"],
    executionMode: "evaluateInline",
    locationType: "policyLocationDomain",
    locationValue: "partner-vendor.com",
    policyActions: [{ action: "evaluateClassification" }],
    restrictionAction: null,
  },
  {
    userId: "user-carol-003",
    userDisplayName: "Carol Chen (Sales)",
    activities: ["uploadText", "downloadText"],
    executionMode: "evaluateInline",
    locationType: "policyLocationApplication",
    locationValue: "Sales Coach (custom-sales-022)",
    policyActions: [],
    restrictionAction: null,
  },
  {
    userId: "user-dave-004",
    userDisplayName: "Dave Wilson (IT)",
    activities: ["uploadFile", "downloadFile"],
    executionMode: "evaluateInline",
    locationType: "policyLocationApplication",
    locationValue: "ServiceNow IT Agent (ext-servicenow-010)",
    policyActions: [],
    restrictionAction: null,
  },
  {
    userId: null,
    userDisplayName: "Tenant-wide Policy",
    activities: ["uploadFile"],
    executionMode: "evaluateOffline",
    locationType: "policyLocationUrl",
    locationValue: "https://external-sharepoint.contoso-partner.com/shared",
    policyActions: [{ action: "restrictAccess", restrictionAction: "audit" }],
    restrictionAction: "audit",
  },
];

// Label drift events — simulates monitoring changes over time
export const demoLabelDrifts = [
  {
    labelId: "a1b2c3d4-0004-4001-8000-000000000001",
    driftType: "ENCRYPTION_CHANGED" as const,
    field: "hasProtection",
    previousValue: "true",
    currentValue: "false",
    severity: "CRITICAL" as const,
    resolved: false,
    hoursAgo: 3,
  },
  {
    labelId: "a1b2c3d4-0003-4001-8000-000000000001",
    driftType: "PRIORITY_CHANGED" as const,
    field: "priority",
    previousValue: "5",
    currentValue: "2",
    severity: "HIGH" as const,
    resolved: false,
    hoursAgo: 8,
  },
  {
    labelId: "a1b2c3d4-0003-4002-8000-000000000002",
    driftType: "SCOPE_CHANGED" as const,
    field: "applicableTo",
    previousValue: "email, file",
    currentValue: "email, file, site, teamwork",
    severity: "MEDIUM" as const,
    resolved: false,
    hoursAgo: 12,
  },
  {
    labelId: "a1b2c3d4-0004-4003-8000-000000000003",
    driftType: "ENDPOINT_PROTECTION_CHANGED" as const,
    field: "isEndpointProtectionEnabled",
    previousValue: "true",
    currentValue: "false",
    severity: "CRITICAL" as const,
    resolved: false,
    hoursAgo: 1,
  },
  {
    labelId: "a1b2c3d4-0002-4001-8000-000000000001",
    driftType: "LABEL_DISABLED" as const,
    field: "isEnabled",
    previousValue: "true",
    currentValue: "false",
    severity: "HIGH" as const,
    resolved: false,
    hoursAgo: 24,
  },
  {
    labelId: "a1b2c3d4-0003-4003-8000-000000000003",
    driftType: "PROTECTION_CHANGED" as const,
    field: "applicationMode",
    previousValue: "manual",
    currentValue: "automatic",
    severity: "MEDIUM" as const,
    resolved: true,
    hoursAgo: 72,
  },
  {
    labelId: "a1b2c3d4-0001-4000-8000-000000000001",
    driftType: "COLOR_CHANGED" as const,
    field: "color",
    previousValue: "#48BB78",
    currentValue: "#38A169",
    severity: "LOW" as const,
    resolved: true,
    hoursAgo: 168,
  },
];
